

//MSVCRT
WINBASEAPI wchar_t* __cdecl MSVCRT$wcstok(wchar_t*  _Str, const wchar_t*  _Delim);
WINBASEAPI wchar_t* __cdecl MSVCRT$wcstok_s(wchar_t* _Str, const wchar_t* _Delim, wchar_t** _Context);
WINBASEAPI wchar_t* __cdecl MSVCRT$wcsstr(const wchar_t* _Str, const wchar_t* _SubStr);
WINBASEAPI wchar_t* __cdecl MSVCRT$wcsrchr(const wchar_t* _Str, wchar_t _Ch);
WINBASEAPI wchar_t* __cdecl MSVCRT$wcsncat(wchar_t*  _Dest, const wchar_t*  _Source, size_t _Count);
WINBASEAPI wchar_t* __cdecl MSVCRT$wcscpy(wchar_t*  _Dest, const wchar_t*  _Source);
WINBASEAPI wchar_t* __cdecl MSVCRT$wcscmp(const wchar_t* _lhs, const wchar_t* _rhs);
WINBASEAPI wchar_t* __cdecl MSVCRT$wcscat(wchar_t*  _Dest, const wchar_t*  _Source);
WINBASEAPI wchar_t* __cdecl MSVCRT$wcsncat(wchar_t*  _Dest, const wchar_t*  _Source, size_t _Count);
WINBASEAPI void* __cdecl MSVCRT$realloc(void* _Memory, size_t _NewSize);
WINBASEAPI void* __cdecl MSVCRT$memcpy(void*  _Dst, const void*  _Src, size_t _MaxCount);
WINBASEAPI void* __cdecl MSVCRT$calloc(size_t _NumOfElements, size_t _SizeOfElements);
WINBASEAPI void __cdecl MSVCRT$memset(void* dest, int c, size_t count);
WINBASEAPI void __cdecl MSVCRT$free(void* _Memory);
WINBASEAPI unsigned long __cdecl MSVCRT$wcstoul(const wchar_t*  _Str, wchar_t**  _EndPtr, int _Radix);
WINBASEAPI unsigned long __cdecl MSVCRT$strtoul(const char*  _Str, char**  _EndPtr, int _Radix);
WINBASEAPI size_t __cdecl MSVCRT$wcslen(const wchar_t* _Str);
WINBASEAPI size_t __cdecl MSVCRT$strnlen(const char* _Str, size_t _MaxCount);
WINBASEAPI size_t __cdecl MSVCRT$strlen(const char* _Str);
WINBASEAPI PCHAR __cdecl MSVCRT$strstr(const char* haystack, const char* needle);
WINBASEAPI PCHAR __cdecl MSVCRT$strchr(const char* haystack, int needle);
WINBASEAPI long __cdecl MSVCRT$_wtol(const wchar_t* str);
WINBASEAPI int __cdecl MSVCRT$vsnprintf(char*  d, size_t n, const char*  format, va_list arg);
WINBASEAPI int __cdecl MSVCRT$swprintf(wchar_t* __stream, const wchar_t* __format, ...);
WINBASEAPI int __cdecl MSVCRT$strncmp(const char* _Str1, const char* _Str2, size_t _MaxCount);
WINBASEAPI int __cdecl MSVCRT$strcmp(const char* _Str1, const char* _Str2);
WINBASEAPI int __cdecl MSVCRT$sprintf(char* __stream, const char* __format, ...);
WINBASEAPI int __cdecl MSVCRT$memcmp(const void* _Buf1, const void* _Buf2, size_t _Size);
WINBASEAPI int __cdecl MSVCRT$_wcsicmp(const wchar_t* _Str1, const wchar_t* _Str2);
WINBASEAPI int __cdecl MSVCRT$_swprintf(wchar_t*  _Dest, const wchar_t*  _Format, ...);
WINBASEAPI int __cdecl MSVCRT$_stricmp(const char* _Str1, const char* _Str2);
WINBASEAPI int __cdecl MSVCRT$_snwprintf(wchar_t*  _Dest, size_t _Count, const wchar_t*  _Format, ...);
WINBASEAPI errno_t __cdecl MSVCRT$wcscpy_s(wchar_t* _Dst, rsize_t _DstSize, const wchar_t* _Src);
WINBASEAPI char* __cdecl MSVCRT$strtok(char*  _Str, const char*  _Delim);
WINBASEAPI char* __cdecl MSVCRT$_ultoa(unsigned long _Value, char* _Dest, int _Radix);
WINBASEAPI char* __cdecl MSVCRT$strcpy(char*  __dst, const char*  __src);
WINBASEAPI _CONST_RETURN wchar_t* __cdecl MSVCRT$wcschr(const wchar_t* _Str, wchar_t _Ch);
DECLSPEC_IMPORT wchar_t* __cdecl MSVCRT$wcstok(wchar_t* _Str, const wchar_t* _Delim);
DECLSPEC_IMPORT wchar_t* __cdecl MSVCRT$wcstok_s(wchar_t* _Str, const wchar_t* _Delim, wchar_t** _Context);
DECLSPEC_IMPORT wchar_t* __cdecl MSVCRT$wcsstr(const wchar_t* _Str, const wchar_t* _SubStr);
DECLSPEC_IMPORT wchar_t* __cdecl MSVCRT$wcsrchr(const wchar_t* _Str, wchar_t _Ch);
DECLSPEC_IMPORT wchar_t* __cdecl MSVCRT$wcsncat(wchar_t* _Dest, const wchar_t* _Source, size_t _Count);
DECLSPEC_IMPORT wchar_t* __cdecl MSVCRT$wcscpy(wchar_t* _Dest, const wchar_t* _Source);
DECLSPEC_IMPORT wchar_t* __cdecl MSVCRT$wcscmp(const wchar_t* _lhs, const wchar_t* _rhs);
DECLSPEC_IMPORT wchar_t* __cdecl MSVCRT$wcscat(wchar_t* _Dest, const wchar_t* _Source);
DECLSPEC_IMPORT void* __cdecl MSVCRT$realloc(void* _Memory, size_t _NewSize);
DECLSPEC_IMPORT void* __cdecl MSVCRT$memcpy(void* Dst, const void* _Src, size_t _MaxCount);
DECLSPEC_IMPORT void* __cdecl MSVCRT$calloc(size_t _NumOfElements, size_t _SizeOfElements);
DECLSPEC_IMPORT void __cdecl MSVCRT$memset(void* dest, int c, size_t count);
DECLSPEC_IMPORT void __cdecl MSVCRT$free(void* _Memory);
DECLSPEC_IMPORT unsigned long __cdecl MSVCRT$wcstoul(const wchar_t* _Str, wchar_t** _EndPtr, int _Radix);
DECLSPEC_IMPORT unsigned long __cdecl MSVCRT$strtoul(const char* _Str, char** _EndPtr, int _Radix);
DECLSPEC_IMPORT size_t __cdecl MSVCRT$wcslen(const wchar_t* _Str);
DECLSPEC_IMPORT size_t __cdecl MSVCRT$strnlen(const char* _Str, size_t _MaxCount);
DECLSPEC_IMPORT size_t __cdecl MSVCRT$strlen(const char* _Str);
DECLSPEC_IMPORT PCHAR __cdecl MSVCRT$strstr(const char* haystack, const char* needle);
DECLSPEC_IMPORT PCHAR __cdecl MSVCRT$strstr(const char* haystack, const char* needle);
DECLSPEC_IMPORT PCHAR __cdecl MSVCRT$strchr(const char* haystack, int needle);
DECLSPEC_IMPORT PCHAR __cdecl MSVCRT$strchr(const char* haystack, int needle);
DECLSPEC_IMPORT int __cdecl MSVCRT$vsnprintf(char* d, size_t n, const char* format, va_list arg);
DECLSPEC_IMPORT int __cdecl MSVCRT$strncmp(const char* _Str1, const char* _Str2, size_t _MaxCount);
DECLSPEC_IMPORT int __cdecl MSVCRT$strcmp(const char* _Str1, const char* _Str2);
DECLSPEC_IMPORT int __cdecl MSVCRT$strcmp(const char* _Str1, const char* _Str2);
DECLSPEC_IMPORT int __cdecl MSVCRT$sprintf(char* __stream, const char* __format, ...);
DECLSPEC_IMPORT int __cdecl MSVCRT$memcmp(const void* _Buf1, const void* _Buf2, size_t _Size);
DECLSPEC_IMPORT int __cdecl MSVCRT$_wcsicmp(const wchar_t* _Str1, const wchar_t* _Str2);
DECLSPEC_IMPORT int __cdecl MSVCRT$_snwprintf(wchar_t* _Dest, size_t _Count, const wchar_t* _Format, ...);
DECLSPEC_IMPORT errno_t __cdecl MSVCRT$wcscpy_s(wchar_t* _Dst, rsize_t _DstSize, const wchar_t* _Src);
DECLSPEC_IMPORT char* __cdecl MSVCRT$strtok(char* _Str, const char* _Delim);
DECLSPEC_IMPORT char* __cdecl MSVCRT$strcpy(char* __dst, const char* __src);
DECLSPEC_IMPORT char* __cdecl MSVCRT$strcat(char* _Dest, const char* _Source);
DECLSPEC_IMPORT char* __cdecl MSVCRT$_ultoa(unsigned long _Value, char* _Dest, int _Radix);
DECLSPEC_IMPORT char* __cdecl MSVCRT$strtok(char*  _Str, const char*  _Delim);
DECLSPEC_IMPORT char* __cdecl MSVCRT$strcpy(char*  __dst, const char*  __src);
DECLSPEC_IMPORT char* __cdecl MSVCRT$strcat(char*  _Dest, const char*  _Source);
DECLSPEC_IMPORT _CONST_RETURN wchar_t* __cdecl MSVCRT$wcschr(const wchar_t* _Str, wchar_t _Ch);
_CRTIMP char* __cdecl MSVCRT$strtok_s(char* _Str, const char* _Delim, char** _Context);
_CRTIMP char* __cdecl MSVCRT$strtok_s(char* _Str, const char* _Delim, char** _Context);
